// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping.Models;

namespace OnlineShopping.Migrations
{
    [DbContext(typeof(OnlineShoppingDBContext))]
    [Migration("20210116134640_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OnlineShopping.Models.Laptops", b =>
                {
                    b.Property<int>("serialNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("specification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("serialNo");

                    b.ToTable("Tbllaptops");

                    b.HasData(
                        new
                        {
                            serialNo = 1,
                            Colour = "Black",
                            Image = "/laptop10.jpg",
                            ModelName = "HP",
                            Price = 45000.0,
                            specification = "10th Gen i3-1005G1/8GB/256GB"
                        },
                        new
                        {
                            serialNo = 2,
                            Colour = "Black",
                            Image = "/laptop11.jpg",
                            ModelName = "Dell",
                            Price = 36990.0,
                            specification = "10th gen Intel Core i3/ 8GB / 1TB"
                        },
                        new
                        {
                            serialNo = 3,
                            Colour = "Platinum Grey",
                            Image = "/laptop19.jpg",
                            ModelName = "Lenovo",
                            Price = 50000.0,
                            specification = "4GB/1TB HDD/Windows 10/MS"
                        },
                        new
                        {
                            serialNo = 4,
                            Colour = "Jet Black",
                            Image = "/laptop20.jpg",
                            ModelName = "HP",
                            Price = 52490.0,
                            specification = "i5-10210U/8GB/512GB "
                        },
                        new
                        {
                            serialNo = 5,
                            Colour = "Silver",
                            Image = "/laptop6.jpg",
                            ModelName = "HP",
                            Price = 45490.0,
                            specification = "Ryzen 5 3450U/8GB/512GB SSD"
                        },
                        new
                        {
                            serialNo = 6,
                            Colour = "Transparent Silver",
                            Image = "/laptop7.jpg",
                            ModelName = "Asus",
                            Price = 25269.0,
                            specification = "4GB RAM/1 TB HDD/Windows 10"
                        },
                        new
                        {
                            serialNo = 7,
                            Colour = "Pure Silver",
                            Image = "/laptop8.jpg",
                            ModelName = "Aser",
                            Price = 28670.0,
                            specification = "4GB Ram/1TB HDD/Window 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
